apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
  clusterIP: None
  selector:
    app: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: registry
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: registry
        image: distribution/distribution:2.8.1
        ports:
        - name: registry
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
