apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  serviceName: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: distribution/distribution:2.8.1
          ports:
            - name: registry
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/registry
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app1
#   labels:
#     app: app1
# spec:
#   clusterIP: None
#   ports:
#     - name: registry
#       port: 5000
#       targetPort: 5000
#       protocol: TCP
#   selector:
#     app: app1
